import { Company } from '@/types/company';

export const COMPANIES: Company[] = [
  {
    slug: 'seek',
    name: 'SEEK Limited',
    shortName: 'SEEK',
    ticker: 'SEK',
    exchange: 'ASX',
    country: 'AU',
    description: 'Australian online employment marketplace operating across Asia-Pacific.',
    website: 'https://www.seek.com.au',
    irPage: 'https://ir.seek.com.au',
    reportingCurrency: 'AUD',
    reportingUnit: 'millions',
    fiscalYearConvention: 'JUL_JUN',
    fiscalYearNote: 'FY ends 30 June',
    periodsAvailable: ['annual', 'half'],
    lastUpdated: '',
  },
  {
    slug: 'kanzhun',
    name: 'Kanzhun Limited',
    shortName: 'BOSS Zhipin',
    ticker: 'BZ',
    exchange: 'NASDAQ',
    country: 'CN',
    description: 'Chinese online recruitment platform operating the BOSS Zhipin app.',
    website: 'https://www.zhipin.com',
    irPage: 'https://ir.kanzhun.com',
    reportingCurrency: 'CNY',
    reportingUnit: 'millions',
    fiscalYearConvention: 'JAN_DEC',
    fiscalYearNote: 'FY ends 31 December',
    periodsAvailable: ['annual', 'quarter'],
    lastUpdated: '',
  },
  {
    slug: 'ziprecruiter',
    name: 'ZipRecruiter, Inc.',
    shortName: 'ZipRecruiter',
    ticker: 'ZIP',
    exchange: 'NASDAQ',
    country: 'US',
    description: 'AI-powered US online employment marketplace connecting employers and job seekers.',
    website: 'https://www.ziprecruiter.com',
    irPage: 'https://investor.ziprecruiter.com',
    reportingCurrency: 'USD',
    reportingUnit: 'thousands',
    fiscalYearConvention: 'JAN_DEC',
    fiscalYearNote: 'FY ends 31 December',
    periodsAvailable: ['annual', 'quarter'],
    lastUpdated: '',
  },
  {
    slug: 'pracuji',
    name: 'Pracuji.cz s.r.o.',
    shortName: 'Pracuji',
    ticker: '',
    exchange: 'PRIVATE',
    country: 'CZ',
    description: 'Czech and Slovak online job board.',
    website: 'https://www.pracuji.cz',
    irPage: '',
    reportingCurrency: 'CZK',
    reportingUnit: 'thousands',
    fiscalYearConvention: 'JAN_DEC',
    fiscalYearNote: 'FY ends 31 December',
    periodsAvailable: ['annual'],
    lastUpdated: '',
  },
  {
    slug: 'recruit-holdings',
    name: 'Recruit Holdings Co., Ltd.',
    shortName: 'Recruit Holdings',
    ticker: '6098',
    exchange: 'TSE',
    country: 'JP',
    description: 'Japanese HR/staffing conglomerate owning Indeed, Glassdoor, and Rikunabi.',
    website: 'https://recruit-holdings.com',
    irPage: 'https://recruit-holdings.com/en/ir/',
    reportingCurrency: 'JPY',
    reportingUnit: 'millions',
    fiscalYearConvention: 'APR_MAR_JP',
    fiscalYearNote: 'FY ends 31 March',
    periodsAvailable: ['annual', 'quarter'],
    lastUpdated: '',
  },
  {
    slug: 'visional',
    name: 'Visional, Inc.',
    shortName: 'Visional',
    ticker: '4194',
    exchange: 'TSE',
    country: 'JP',
    description: 'Japanese HR tech holding company operating Bizreach and BizHint platforms.',
    website: 'https://visional.inc',
    irPage: 'https://visional.inc/en/ir/',
    reportingCurrency: 'JPY',
    reportingUnit: 'millions',
    fiscalYearConvention: 'APR_MAR_JP',
    fiscalYearNote: 'FY ends 31 July',
    periodsAvailable: ['annual', 'quarter'],
    lastUpdated: '',
  },
  {
    slug: 'infoedge',
    name: 'Info Edge (India) Limited',
    shortName: 'Naukri',
    ticker: 'NAUKRI',
    exchange: 'NSE',
    country: 'IN',
    description: 'Indian online classifieds company operating Naukri.com, 99acres, and Jeevansathi.',
    website: 'https://infoedge.in',
    irPage: 'https://infoedge.in/investor-relations.htm',
    reportingCurrency: 'INR',
    reportingUnit: 'millions',
    fiscalYearConvention: 'APR_MAR',
    fiscalYearNote: 'FY ends 31 March',
    periodsAvailable: ['annual', 'quarter'],
    lastUpdated: '',
  },
];

export const COMPANY_SLUGS = COMPANIES.map((c) => c.slug);

export function getCompany(slug: string): Company | undefined {
  return COMPANIES.find((c) => c.slug === slug);
}
